"""Add reserva_id to Jugador

Revision ID: 2692b8317059
Revises: d40fe20d359e
Create Date: 2024-08-13 10:06:06.234259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2692b8317059'
down_revision: Union[str, None] = 'd40fe20d359e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_jugadores_reserva_id_reservas'), 'reservas', ['reserva_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jugadores_reserva_id_reservas'), type_='foreignkey')
        batch_op.drop_column('reserva_id')
    # ### end Alembic commands ###