"""Add reserva_id to jugadores with batch mode

Revision ID: 357b6202dd69
Revises: f7c85d81bac8
Create Date: 2024-08-13 10:43:43.177213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357b6202dd69'
down_revision: Union[str, None] = 'f7c85d81bac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
