"""Add lastname column to socios

Revision ID: 5720c68e82d2
Revises: bd83bc405702
Create Date: 2024-07-30 18:32:12.398730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5720c68e82d2'
down_revision: Union[str, None] = 'bd83bc405702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('socios', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('socios', sa.Column('type', sa.String(), nullable=True))
    op.drop_index('ix_socios_apellido', table_name='socios')
    op.create_index(op.f('ix_socios_lastname'), 'socios', ['lastname'], unique=False)
    op.create_index(op.f('ix_socios_phone'), 'socios', ['phone'], unique=False)
    op.create_index(op.f('ix_socios_type'), 'socios', ['type'], unique=False)
    op.drop_column('socios', 'apellido')
    op.drop_column('socios', 'telefono')
    op.drop_column('socios', 'tipo_socio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('tipo_socio', sa.VARCHAR(), nullable=True))
    op.add_column('socios', sa.Column('telefono', sa.VARCHAR(), nullable=True))
    op.add_column('socios', sa.Column('apellido', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_socios_type'), table_name='socios')
    op.drop_index(op.f('ix_socios_phone'), table_name='socios')
    op.drop_index(op.f('ix_socios_lastname'), table_name='socios')
    op.create_index('ix_socios_apellido', 'socios', ['apellido'], unique=False)
    op.drop_column('socios', 'type')
    op.drop_column('socios', 'phone')
    op.drop_column('socios', 'lastname')
    # ### end Alembic commands ###
