"""Initial migration

Revision ID: bd83bc405702
Revises: 
Create Date: 2024-07-30 15:16:17.192451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd83bc405702'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=True)
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('tipo_jugador', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jugadores_apellido'), 'jugadores', ['apellido'], unique=False)
    op.create_index(op.f('ix_jugadores_id'), 'jugadores', ['id'], unique=False)
    op.create_index(op.f('ix_jugadores_name'), 'jugadores', ['name'], unique=False)
    op.create_table('pistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tipo_pista', sa.String(), nullable=True),
    sa.Column('tiempo_juego', sa.Integer(), nullable=True),
    sa.Column('individuales', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pistas_id'), 'pistas', ['id'], unique=False)
    op.create_index(op.f('ix_pistas_name'), 'pistas', ['name'], unique=False)
    op.create_table('socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('tipo_socio', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socios_apellido'), 'socios', ['apellido'], unique=False)
    op.create_index(op.f('ix_socios_email'), 'socios', ['email'], unique=True)
    op.create_index(op.f('ix_socios_id'), 'socios', ['id'], unique=False)
    op.create_index(op.f('ix_socios_name'), 'socios', ['name'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pista_id', sa.Integer(), nullable=True),
    sa.Column('dia', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fin', sa.DateTime(), nullable=True),
    sa.Column('individuales', sa.Boolean(), nullable=True),
    sa.Column('jugador1_id', sa.Integer(), nullable=True),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('jugador3_id', sa.Integer(), nullable=True),
    sa.Column('jugador4_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jugador1_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador3_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['jugador4_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['pista_id'], ['pistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_dia'), 'reservas', ['dia'], unique=False)
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_dia'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_socios_name'), table_name='socios')
    op.drop_index(op.f('ix_socios_id'), table_name='socios')
    op.drop_index(op.f('ix_socios_email'), table_name='socios')
    op.drop_index(op.f('ix_socios_apellido'), table_name='socios')
    op.drop_table('socios')
    op.drop_index(op.f('ix_pistas_name'), table_name='pistas')
    op.drop_index(op.f('ix_pistas_id'), table_name='pistas')
    op.drop_table('pistas')
    op.drop_index(op.f('ix_jugadores_name'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_id'), table_name='jugadores')
    op.drop_index(op.f('ix_jugadores_apellido'), table_name='jugadores')
    op.drop_table('jugadores')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
