"""Add reserva_id to jugadores

Revision ID: f7c85d81bac8
Revises: 03213c8e4b99
Create Date: 2024-08-13 10:35:31.656107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c85d81bac8'
down_revision: Union[str, None] = '03213c8e4b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
